services:
  - type: web
    name: skillstarter-frontend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    rootDir: frontend
    envVars:
      - key: NODE_ENV
        value: production
