services:
  - type: web
    name: skillstarter-1
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables here
